# Generated by Django 5.0.6 on 2024-07-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='ArticleHiveUser', max_length=15),
        ),
    ]
