# Generated by Django 5.0.6 on 2024-07-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='ArticleHiveUser', max_length=15),
        ),
    ]
