# Generated by Django 5.0.6 on 2024-07-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='name',
        ),
    ]
