# Generated by Django 5.0.6 on 2024-07-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0005_rename_user_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='contact',
        ),
    ]
