# Generated by Django 5.0.7 on 2024-07-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=500)),
                ('date_replied', models.DateTimeField(auto_now=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_reply', to='article_hive_app.comment')),
            ],
        ),
    ]
