# Generated by Django 5.0.6 on 2024-07-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0015_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutme',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
