#!/bin/bash

# for production home is $HOME

git pull

sleep 2

activate_venv="$(find $HOME -name "activate")"

echo "activate: $activate_venv"
source "$activate_venv"
echo "activated virtual environment ..."
echo ""

sleep 2

maka_and_migrate="$(find $HOME -name "manage.py")"

echo "manage_py_file_path: $maka_and_migrate"
maka_and_migrate="${maka_and_migrate%/*}"
cd "$maka_and_migrate"
python manage.py makemigrations
sleep 2
python manage.py migrate
echo ""
echo "database configurations updated ..."
echo ""
sleep 2

requirement_file_path="$(find $HOME -name "requirements.txt")"

echo "requirement_file_path: $requirement_file_path"
requirement_file_path="${requirement_file_path%/*}"
cd "$requirement_file_path"
pip install -r requirements.txt
echo ""
echo "installed dependencies ..."
echo ""
