# Generated by Django 5.0.6 on 2024-07-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0009_remove_user_joined_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
