# Generated by Django 5.0.6 on 2024-07-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0011_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
