# Generated by Django 5.0.6 on 2024-07-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0017_rename_created_at_comment_date_commented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../static/images/placeholder.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
