# Generated by Django 5.0.6 on 2024-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0018_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/placeholder.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
