# Generated by Django 5.0.6 on 2024-07-08 08:47

import article_hive_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0019_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/placeholder.png', null=True, upload_to=article_hive_app.models.unique_profile_pic),
        ),
    ]
