# Generated by Django 5.0.6 on 2024-07-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_hive_app', '0020_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
